### ISSUE TITLE
Diseño de vistaProducto.html

### ISSUE THREAD

**Issue by lazamartinez** [joaquinkuster/ecomisiones#15]
Descripción de la historia de usuario
Como cliente,

- Quiero poder observar el producto al cual quiero agregarle al carrito

Criterios de aceptación
Listado:

- El sistema debe mostrar el nombre de producto y la cantidad del descuento si es que existe
- El sistema debe ser capaz de calcular y mostrar en pantalla el precio con descuento
- El cliente puede comprar por cantidad dependiendo del stock disponible
- El cliente puede agregar al carrito dependiendo del stock disponible
- El cliente puede acceder a los productos relacionados con el producto que quiere comprar

**Comment by MindfulLearner** [comment]
Ehy need help whats the issue?
